version: '3'
services:
  wordpress_test:
    build: ./wp-image
    image: harrinsonmb/wordpress
    ports:
    - "8080:80"
    volumes:
    - ./wp-app:/var/www/html
    environment:
        #XDEBUG_CONFIG: "remote_host=192.168.1.146"
        PHP_IDE_CONFIG: "serverName=docker-server"